name: Environment and Variables

on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Print image link
        run: echo ${{ vars.VITE_IMG_LINK }}

  job2:
    runs-on: ubuntu-latest
    environment: github-pages
    env:
      VITE_IMG_LINK: ${{ vars.VITE_IMG_LINK }}
    steps:
      - name: Print channel name
        run: echo Channel name is ${{ env.VITE_IMG_LINK }}
