name: Echo Variable

on:
  workflow_dispatch:

jobs:
  echo-var:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Echo from vars
        run: echo "OWNER is ${{ vars.OWNER }}"