name: Echo Variable

on:
  workflow_dispatch:

jobs:
  echo-var:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Echo VITE_IMG_LINK from vars
        run: echo "VITE_IMG_LINK is ${{ vars.VITE_IMG_LINK }}"